# Generated by Django 5.2 on 2025-05-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='file_type',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='file_name',
            field=models.CharField(default='file', max_length=120),
            preserve_default=False,
        ),
    ]
