# Generated by Django 5.2 on 2025-05-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_mediafile_file_type_mediafile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='file_type', max_length=10),
            preserve_default=False,
        ),
    ]
