# Generated by Django 5.2.1 on 2025-05-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_mediafile_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='file',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='end_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='start_file',
            field=models.FileField(default='default.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
