# Generated by Django 5.2.1 on 2025-05-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_mediafile_file_mediafile_end_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedface',
            name='bounding_box',
        ),
        migrations.RemoveField(
            model_name='detectedface',
            name='confidence',
        ),
        migrations.AddField(
            model_name='detectedface',
            name='data',
            field=models.JSONField(default='f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detectedface',
            name='name',
            field=models.CharField(default='name', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediafile',
            name='landmarks_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
