# Generated by Django 5.2.1 on 2025-05-11 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_detectedface_bounding_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
